language: php
sudo: false
dist: trusty
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
before_script:
  - if find . -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n 1 -P 8 php -l | grep -v "No syntax errors detected"; then exit 1; fi
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script: phpunit